# Generated by Django 4.1.2 on 2022-10-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last_name'),
        ),
    ]
